runtime: nodejs20

instance_class: F1

env_variables:
  PORT: 8080
  NODE_ENV: production

build_env_variables:
  NPM_CONFIG_FORCE: true
  GOOGLE_NODE_RUN_SCRIPTS: ''

includes:
  - app-secret.yaml

handlers:
  - url: /build
    static_dir: public/build

entrypoint: npx remix-serve ./build/server/index.js
