runtime: nodejs20

instance_class: F1

env_variables:
  PORT: 8080
  NODE_ENV: production

includes:
  - app_secret.yaml

handlers:
  - url: /build
    static_dir: public/build

entrypoint: npx remix-serve ./build/index.js
