version: '3.1'

services:

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: favoms
      POSTGRES_USER: favoms
      POSTGRES_PASSWORD: favoms
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - favoms_volume:/var/lib/postgresql/data

volumes:
  favoms_volume:
