name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    concurrency:
      group: deploy
      cancel-in-progress: false

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci --force

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/708563497308/locations/global/workloadIdentityPools/favoms-pool/providers/github-actions
          service_account: favoms-delivery@favoms.iam.gserviceaccount.com

      - uses: google-github-actions/setup-gcloud@v2

      - run: envsubst < app-secret.yaml.sample > app-secret.yaml
        env:
          FAVOMS_DB_URL: ${{ secrets.FAVOMS_DB_URL }}

      - run: make deploy

      - run: rm -rf ./app-secret.yaml ./deploy
        if: ${{ always() }}
